name: Contracts
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    services:
      mina-local-network:
        image: o1labs/mina-local-network:compatible-latest-lightnet
        env:
          NETWORK_TYPE: "single-node"
          PROOF_LEVEL: "none"
          LOG_LEVEL: "Info"
        ports:
          - 3085:3085
          - 5432:5432
          - 8080:8080
          - 8181:8181
          - 8282:8282
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun run lint
      - name: Build lib
        run: |
            cd packages/contracts
            bun run build
      - name: Test lib--secp256k1
        run: |
            export SKIP_PROOFS=true
            cd packages/contracts
            bun run test
      - name: Test lib--secp256r1
        run: |
            export SKIP_PROOFS=true
            export SECP256R1=true
            cd packages/contracts
            bun run test
